### ISSUE TITLE
Make QtWidgets to be an optional dependence

### ISSUE THREAD

**Issue by Kaffeine** [TelepathyIM/telepathy-qt#15]

**Comment by gkiagia** [comment]
Do we actually depend on QtWidgets? and if so, why?

**Comment by Kaffeine** [comment]
@gkiagia Short answer: examples.

**Comment by Kaffeine** [comment]
https://github.com/TelepathyIM/telepathy-qt/commit/025639ec6ad994d8b22a73fb4dca257803dd5cb5
