### ISSUE TITLE
Improve documentation for linux newbies

### ISSUE THREAD

**Issue by ProphetDaniel** [TelepathyIM/telepathy-qt#24]
More clear documentation would help linux newbies to solve the problems.

**Comment by ProphetDaniel** [comment]
This is the result after isssueing cmake command:

`Package QtCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `QtCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'QtCore' found
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- PythonLibrary find version: 2.5
-- Found Python executable: /usr/bin/python2
-- Found Python version: 2.7.12
-- Python 2.7 found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named dbus.mainloop.glib
-- Checking for module 'telepathy-glib>=0.18.0'
--   
-- Telepathy-glib not found or its version is < 0.18.0
-- Checking for module 'glib-2.0'
--   No package 'glib-2.0' found
-- Could NOT find GLIB2 (missing:  GLIB2_LIBRARIES GLIB2_MAIN_INCLUDE_DIR) 
-- Checking for module 'gobject-2.0'
--   No package 'gobject-2.0' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  cmake/modules/FindGObject.cmake:24 (PKG_CHECK_MODULES)
  CMakeLists.txt:175 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/jon/Applications/Linux/telepathy-qt-0.9.7/CMakeFiles/CMakeOutput.log".
See also "/home/jon/Applications/Linux/telepathy-qt-0.9.7/CMakeFiles/CMakeError.log".`

**Comment by Kaffeine** [comment]
Hello Daniel,
Sadly, there is no a single instruction, which can 'fit all'. The solution depends on your distribution.

If you use ubuntu-based distribution (may be it will work for all debian-based distros), then you need to do something like this (I will provide the exact command this Monday):
```sudo apt-get build-dep libtelepathy-qt5```
In Gentoo you'll have everything needed 'out of the box'.

I want to prevent you from further disappointment, so I have to ask: what do you want to do after installation? Why you do not use a distribution-specific package and trying to build it from sources?
I see only few reasons to install Telepathy-Qt from sources: development, testing and packaging. All of the reasons imply that you don't need an installation documentation and can build the project on your own.

**Comment by ProphetDaniel** [comment]
I got frustrated after trying to make my KDE neon Kontact application to work flawlessly with all social networks and instant messaging providers telepathy is able to add in theory. I actually think it would be a waste of my time trying to fix somethiing which should be working right out of the box once installed the distro's image.

As KDE neon is ubuntu based you are right.
In that case your advice works for me. I didn't have this build-dep trick in my arsenal yet. Thank you. Maybe I will be luckier next time I give it a try.
