### ISSUE TITLE
use GNUInstallDirs

### ISSUE THREAD

**Issue by DerDakon** [TelepathyIM/telepathy-qt#30]
GNUInstallDirs.cmake has correct default for all sorts of directories, it also handles things like lib/lib32/lib64/… automagically. Porting to this module is advisable, it makes things much more portable. It also has a mechanism for users to override these defaults if necessary, which is also one that can be used on all projects using this modules.

Using the CMAKE_INSTALL_FULL_* variables of this module in the generated .pc file is advisable as it is the only way that things will work if e.g. the include dir is placed outside of ${prefix}.

**Comment by Kaffeine** [comment]
I think we'll fix this in a few days. This task is easy to implement but hard to test.

**Comment by Kaffeine** [comment]
It seems that anything related to the CMake mess is not `Easy`. Any change leads to a number of other wanted refactoring. I need to get some more experience in CMake before taking this task.
Maybe it will be easier to rewrite from scratch than to update step-by-step. We need to make a new release with Python 3 support (already merged) and it would be much better to release with proper export for CMake targets.

**Comment by Kaffeine** [comment]
Hi @DerDakon,

I pushed a [commit](https://github.com/TelepathyIM/telepathy-qt/commit/f6b5768d644663307a08b1741cb9f22d22d4d066) with GNUInstallDirs to the `staging` branch. Would you mind to test if it works for you? I did some local testing, but it definitely worth to test better.

**Comment by Kaffeine** [comment]
@DerDakon, thank you for the inline comment. It seems that I also messed up the commits during rebase, so the referenced commit had extra changes.

I force-pushed the branch, the new/fixed GNUInstallDirs commit ref is https://github.com/TelepathyIM/telepathy-qt/commit/019018e4bd4ab0274eda5cde021e92c3c6eb7f34

**Comment by DerDakon** [comment]
Works for me.

**Comment by Kaffeine** [comment]
https://github.com/TelepathyIM/telepathy-qt/commit/5f9d4fb3285a6d5e34ea99b2350a879f5f3f7ecd
